language: go
go:
 - 1.3.2
 - 1.4.2
 - 1.5.1
 - release
 - tip

before_script:
  - go get github.com/stretchr/testify/assert
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  
script:
 - go test -v ./...
 - $HOME/gopath/bin/goveralls -service=travis-ci
